=== Estefaniamun/EjerciciosLMSGI/examenes_de_prueba/electrodomesticos.dtd
<!--Declaracion de elementos y su estructura-->
<!ELEMENT electrodomesticos (#PCDATA | electrodomestico | cocina)*>
<!ELEMENT electrodomestico (nevera, horno, microondas, lavadora+, congelador?)*>
<!ELEMENT nevera (#PCDATA)>
<!ELEMENT horno (#PCDATA)>
<!ELEMENT microondas (#PCDATA)>
<!ELEMENT lavadora (#PCDATA)>
<!ELEMENT congelador EMPTY>
<!ELEMENT cocina (amplia?, (reformada | noreformada))*>
<!ELEMENT reformada EMPTY>
<!ELEMENT noreformada EMPTY>
<!ELEMENT amplia EMPTY>
<!--Declaracion de la entidad parametro-->
<!ENTITY % caracteristicas "codigo ID #REQUIRED marca ID #REQUIRED  peso CDATA #REQUIRED">
<!-- Declaracion de los atributos incluyendo la entidad parametro-->

<!ATTLIST nevera %caracteristicas;
                    nivelcongelador ID #IMPLIED>

<!ATTLIST horno %caracteristicas;>

<!ATTLIST microondas %caracteristicas;>
<!ATTLIST lavadora %caracteristicas;
                    kilos CDATA #FIXED "8KG">

<!ATTLIST congelador %caracteristicas;
                        niveles IDREF #REQUIRED>


<!ATTLIST cocina electrodomestico CDATA #REQUIRED
                    codigo IDREFS #REQUIRED
                    estilo (moderna | vintage) "moderna">

=== Estefaniamun/EjerciciosLMSGI/examenes_de_prueba/electrodomesticos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE electrodomesticos SYSTEM "electrodomesticos.dtd">
<electrodomesticos> Electrodomesticos Actuales
    <electrodomestico>
        <nevera  codigo="NSsiemens" marca="siemens" peso="50KG" nivelcongelador="N5">Frigorifico</nevera>
        <horno codigo="HAasus" marca="asus" peso="30KG">Horno peque√±o</horno>
        <microondas codigo="MSsamsung" marca="samsung" peso="20KG" >Microondas incorporado en el mueble</microondas>
        <lavadora codigo="LLG" marca="LG" peso="50KG" kilos="8KG">Lavadora moderna</lavadora>
        <congelador codigo="CFM" marca="FM" peso="50KG" niveles="N5"></congelador>
    </electrodomestico>
    <cocina electrodomestico="nevera" codigo="NSsiemens" estilo="moderna">
        <amplia />
        <reformada />
    </cocina>
    <cocina electrodomestico="microondas" codigo="MSsamsung" estilo="moderna">
        <amplia />
       <reformada /> 
    </cocina>
    <cocina electrodomestico="horno" codigo="HAasus" estilo="vintage">
        <noreformada />
    </cocina>
     <cocina electrodomestico="lavadora" codigo="LLG" estilo="moderna">
         <amplia />
         <noreformada />
     </cocina>

</electrodomesticos>
